spring:
  application:
    name: code-hackathon-app
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/hackathon-project
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true